FROM ft-rails:on-build

EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

# 1.docker build --tag ft-rails:on-build ft_rails/
# 2. git clone https://bitbucket.org/railstutorial/sample_app_4th_ed.git app
# 3. docker build --tag ex02app .
# 4. docker run -it --rm -p 3000:3000 ex02app